version: '3.9'
volumes:
  data:
services:
  app:
    volumes:
      - '.:/app'
    cap_add:
      - SYS_PTRACE
    working_dir: /app
    networks:
      - php-project
  composer:
    image: "composer"
    volumes:
      - '.:/app'
    depends_on:
      - app
    command: install
    working_dir: /app
networks:
  php-project:
