version: '3.9'
services:
  php:
    labels:
      type: app
    image: cr.selcloud.ru/tests/php-project:latest
    working_dir: /var/www/html
    deploy:
      mode: replicated
      replicas: 1
  mysql:
    labels:
      type: db
    image: cr.selcloud.ru/tests/mysql-project:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '${FORWARD_DB_PORT:-0}:3306'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-test}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-test}'
      MYSQL_USER: '${DB_USERNAME:-test}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-test}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
volumes:
  sail-mysql:
    driver: local
