version: '3.8'
services:
  nginx:
    image: nginx:1.22
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.fandeco.org`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    ports:
      - 13900:80
    networks:
      - traefik_traefik-public

networks:
  traefik_traefik-public:
    external: true
