version: '3.8'
services:
  nginx:
    image: nginx:1.22
    container_name: nginx
    labels:
      - "traefik.http.routers.nginx.rule=Host(`dev.fandeco.org`)"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
