version: '3.9'
services:
  php:
    labels:
      type: app
    image: cr.selcloud.ru/tests/php-project:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - sail
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-13306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-test}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-test}'
      MYSQL_USER: '${DB_USERNAME:-test}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-test}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
