version: '3.9'
services:
  app:
    image: cr.selcloud.ru/tests/php-project:latest
    cap_add:
      - SYS_PTRACE
    working_dir: /app
    volumes:
      - '.:/app'
    networks:
      - php-project
networks:
  php-project:
